search_it addon support added + extension point added
FriendsOfREDAXO/minify pull request #35
Opened 2017-04-20 07:02 UTC by palber

Wenn das HTML minifiziert wird, werden die  Kommentare, welche bei der Indexierung verwendet werden, entfernt. Somit wird ab search_it 6.3 nichts indexiert.

2017-04-21 13:53 UTC, phoebusryan requested changes

2017-04-21 13:53 UTC, phoebusryan commented on boot.php
> +					if(rex_addon::get("search_it")->isInstalled())
hier müsste es:

`if(rex_addon::get("search_it")->isAvailable())`

heissen... damit nicht nur geprüft wird, ob das Addon installiert ist, sondern auch ob es aktiviert ist.

2017-04-21 14:23 UTC, palber commented on boot.php
> +					if(rex_addon::get("search_it")->isInstalled())
Danke - werde ich gleich anpassen!

2017-04-21 14:25 UTC, palber commented
Habe den PR wie gewünscht angepasst.
Hast du die Changes von lexplatt hier zusammengeführt oder sind die durch mich hier hergekommen?

2017-04-21 14:55 UTC, phoebusryan commented
die kamen wohl durch dich. ich habe bisher nur ein review gesetzt ;)

2017-04-21 15:12 UTC, palber commented
hmm - kannst du die mit übernehmen oder lieber nen neuen PR?

2017-04-24 05:47 UTC, phoebusryan commented
lieber ein separater pr!

2017-04-24 09:57 UTC, closed without merging